version: '3.9'
services: 
  postgres:
    image: postgres
    restart: always
    environment: 
        - POSTGRES_HOST=database
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
    ports: 
        - "5432:5432"
    volumes: 
        - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql